formatting:
  active: true
  autoCorrect: true
  android: true
  # https://detekt.dev/docs/rules/formatting/#finalnewline
  FinalNewline:
    active: false
  # https://detekt.dev/docs/rules/formatting/#multilineifelse
  MultiLineIfElse:
    active: true
  # https://detekt.dev/docs/rules/formatting/#argumentlistwrapping
  ArgumentListWrapping:
    active: true
  # https://detekt.dev/docs/rules/formatting/#maximumlinelength
  # Disabled because it is also contained in style rules
  MaximumLineLength:
    active: false
  # https://detekt.dev/docs/rules/formatting/#annotationonseparateline
  # Disabled because also multiple annotations on function parameters are reported
  AnnotationOnSeparateLine:
    active: false
  # https://detekt.dev/docs/rules/formatting/#trailingcommaoncallsite
  TrailingCommaOnCallSite:
    active: true
  # https://detekt.dev/docs/rules/formatting/#trailingcommaondeclarationsite
  TrailingCommaOnDeclarationSite:
    active: true
naming:
  # https://detekt.dev/docs/rules/naming/#invalidpackagedeclaration
  InvalidPackageDeclaration:
    active: true
  # https://detekt.dev/docs/rules/naming/#functionnaming
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
style:
  # https://detekt.dev/docs/rules/style/#newlineatendoffile
  NewLineAtEndOfFile:
    active: false
  # https://detekt.dev/docs/rules/style/#forbiddencomment
  ForbiddenComment:
    active: false
  # https://detekt.dev/docs/rules/style/#wildcardimport
  WildcardImport:
    active: false
  # https://detekt.dev/docs/rules/style#unusedprivatemember
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'PreviewScreen', 'PreviewComponent' ]
exceptions:
  active: true
  # https://detekt.dev/docs/rules/exceptions/#toogenericexceptioncaught
  TooGenericExceptionCaught:
    active: false
complexity:
  # https://detekt.dev/docs/rules/complexity#longparameterlist
  LongParameterList:
    active: false
  # https://detekt.dev/docs/rules/complexity/#longmethod
  LongMethod:
    ignoreAnnotated: [ 'Composable' ]
    threshold: 200
  # https://detekt.dev/docs/rules/complexity/#cyclomaticcomplexmethod
  CyclomaticComplexMethod:
    threshold: 20
    ignoreAnnotated: [ 'Composable' ]
    # Ignores a complex method if it only contains a single when expression.
    ignoreSingleWhenExpression: true
    # Ignores simple (braceless) when entries
    ignoreSimpleWhenEntries: true
Compose:
  # https://github.com/mrmans0n/compose-rules
  # https://mrmans0n.github.io/compose-rules/rules/#compositionlocals
  CompositionLocalAllowlist:
    active: true
    # Define a list of CompositionLocals that are allowed here
    allowedCompositionLocals: LocalAppColors,LocalAppTypography,LocalAppShapes,LocalAppDimens,LocalAppAlpha
  # https://mrmans0n.github.io/compose-rules/rules/#naming-multipreview-annotations-properly
  PreviewNaming:
    active: false
    # to stay aligned with "official" preview names
  # https://mrmans0n.github.io/compose-rules/rules/#avoid-using-unstable-collections
  UnstableCollections:
    active: false